---
title: "A Prediction of 2019 Canadian Federal Election Result based on CES and Post-Stratification dataset while assuming there is no missing vote"
author: "Yutong Wu"
date: "December 22nd, 2020 "
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages("haven")
library(haven)
library(tidyverse)
# Loading in the survey Data and transform it to csv file
survey_data = read_dta("2019_CES.dta")
write.csv(survey_data, file = "2019_CES.csv")


# Loading in the census Data
census_data <- read_csv("CensusProfile2016.csv")
```

## Keywords:
2019 Canadian Federal election, Multilevel regression with poststratification Model, Observational Study

## Data
The survey data is obtained from Harverd Dataverse which was collected through online questionnaire. While the census data is obtained from Statistics Canada who conducts a census every five years. So the census data recorded the responds of public in 2016 which may lead to an avoidless bias. 


## Reference
- Hadley Wickham and Evan Miller (2020). haven: Import and Export 'SPSS', 'Stata' and 'SAS' Files. R package version 2.3.1. https://CRAN.R-project.org/package=haven

- Wickham et al., (2019). Welcome to the tidyverse. Journal of Open Source Software, 4(43), 1686, https://doi.org/10.21105/joss.01686

- Stephenson, Laura B; Harell, Allison; Rubenson, Daniel; Loewen, Peter John, 2020, "2019 Canadian Election Study - Online Survey", https://doi.org/10.7910/DVN/DUS88V, Harvard Dataverse, V1

- Statistics Canada. (2003).Census Profile, 2016 Census, https://www12.statcan.gc.ca/census-recensement/2016/dp-pd/prof/details/page_Download-Telecharger.cfm?Lang=E&Tab=1&Geo1=PR&Code1=01&Geo2=PR&Code2=01&SearchText=01&SearchType=Begins&SearchPR=01&B1=All&TABID=3&type=0

- Allaire J, Xie Y, McPherson J, Luraschi J, Ushey K, Atkins A, Wickham H, Cheng J, Chang W, Iannone R (2020). rmarkdown: Dynamic Documents for R. R package version 2.6, https://github.com/rstudio/rmarkdown.
